apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-pod
  template:
    metadata:
      labels:
        app: gateway-pod
    spec:
      containers:
        - name: gateway-container
          image: 192.168.3.1:5000/gateway
          ports:
            - containerPort: 7777
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway-pod
  ports:
    - port: 7777
      targetPort: 7777
      nodePort: 30011
  type: NodePort
