apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-payement
spec:
  capacity:
    storage: 120Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mysql"  # Ensure this path exists on the node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-payement-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-payement-depy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-payement-pod
  template:
    metadata:
      labels:
        app: mysql-payement-pod
    spec:
      containers:
       - image: mysql
         name: mysql-payement-container
         imagePullPolicy: Always   
         env:
            - name: "MYSQL_DATABASE"
              valueFrom: 
                secretKeyRef:
                  name: mysql-secret
                  key: BDD

            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom: 
                secretKeyRef:
                  name: mysql-secret
                  key: ROOT_PASSWORD

            - name: "MYSQL_ROOT_USER"
              value: "root"
         ports:
           - containerPort: 3306
         
         volumeMounts:
           - name: mysql-with-secret-persistent-storage
             mountPath: /var/lib/mysql_payement

           
      volumes:
      - name: mysql-with-secret-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-payement-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-payement-srv
spec:
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30059
  selector:
    app: mysql-payement-pod

  type: NodePort    
