apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-optimization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-optimization-pod
  template:
    metadata:
      labels:
        app: ms-optimization-pod
    spec:
      containers:
        - name: ms-optimization-container
          image: 192.168.3.1:5000/ms-optimization
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ms-optimization
spec:
  selector:
    app: ms-optimization-pod
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30015
  type: NodePort
